name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Check if version has been incremented compared to main branch
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")

          git fetch origin main
          git checkout origin/main -- package.json
          MAIN_VERSION=$(node -p "require('./package.json').version")

          git checkout -- package.json

          HIGHEST_VERSION=$(echo -e "$CURRENT_VERSION\n$MAIN_VERSION" | sort -V | tail -n1)

          if [ "$CURRENT_VERSION" = "$MAIN_VERSION" ]; then
            echo "Error: Version in package.json ($CURRENT_VERSION) has not been incremented compared to main branch ($MAIN_VERSION)."
            exit 1
            elif [ "$HIGHEST_VERSION" != "$CURRENT_VERSION" ]; then
          echo "Error: Version in package.json ($CURRENT_VERSION) is not the highest compared to main branch ($MAIN_VERSION)."
            exit 1
            else
            echo "Version in package.json ($CURRENT_VERSION) is higher than on the main branch ($MAIN_VERSION)."
            fi
  check-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check if CHANGELOG.md has been updated
        run: |
          VERSION_IN_PACKAGE_JSON=$(node -p "require('./package.json').version")

          if ! grep -qE "# \[?$VERSION_IN_PACKAGE_JSON\]?" CHANGELOG.md; then
          echo "Error: CHANGELOG.md has not been updated for version $VERSION_IN_PACKAGE_JSON."
          exit 1
          else
          echo "CHANGELOG.md has been updated for version $VERSION_IN_PACKAGE_JSON."
          fi
  validation:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t format:check stylelint lint test build --base=origin/main --head=HEAD --exclude='!scope:app' --nxBail=true --parallel=5
