name: deploy

on:
  workflow_dispatch:
    branches:
      - main
      - '!dependabot/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'refs/heads/main'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org/'

      - run: npm ci

      - name: Move dist/libs contents to project root
        run: |
          mkdir -p dist_temp
          cp -R dist/libs/* dist_temp/
          mv dist_temp/* ./
          rm -rf dist_temp

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
